-- MOD-19 (Luca 10/08) — TIPO 'sprint' 🔥: comunicazione di CARICA (countdown
-- 3-2-1 → SPRINT! + frase motivazionale dal CALDERONE sopra la card).
--
-- 1) sesto tipo nel CHECK (stesso pattern di mig. 154/159: DROP+ADD).
-- 2) tabella sprint_frasi: il calderone (~200 frasi), amministrabile dal
--    pannello (aggiungi/modifica/spegni). MAI ripetute: alla CREAZIONE di una
--    comunicazione sprint si pesca la frase attiva con MENO usi (spareggio:
--    uso più vecchio), si congela su comunicazioni.sprint_frase (tutti vedono
--    la stessa) e si incrementa usi/ultimo_uso. Esaurito il giro, si riparte
--    dalle meno usate.
-- 3) comunicazioni.sprint_frase: la frase scelta, congelata sulla riga.
-- Idempotente.

ALTER TABLE public.comunicazioni DROP CONSTRAINT IF EXISTS comunicazioni_type_check;
ALTER TABLE public.comunicazioni ADD CONSTRAINT comunicazioni_type_check
    CHECK (type = ANY (ARRAY['info'::text, 'warning'::text, 'success'::text, 'update'::text, 'novita'::text, 'sprint'::text]));

ALTER TABLE public.comunicazioni ADD COLUMN IF NOT EXISTS sprint_frase TEXT;

CREATE TABLE IF NOT EXISTS public.sprint_frasi (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    testo TEXT NOT NULL UNIQUE,
    attivo BOOLEAN NOT NULL DEFAULT true,
    usi INT NOT NULL DEFAULT 0,
    ultimo_uso TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.sprint_frasi ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon sprint_frasi" ON public.sprint_frasi;
CREATE POLICY "Allow anon sprint_frasi" ON public.sprint_frasi FOR ALL USING (true) WITH CHECK (true);

-- ── IL CALDERONE: 200 frasi (le più forti di sempre + taglio vendita) ──
INSERT INTO public.sprint_frasi (testo) VALUES
  ('I record esistono per essere polverizzati.'),
  ('Nessuno si ricorda di chi è arrivato secondo.'),
  ('O trovi un modo, o trovi una scusa.'),
  ('La fatica di oggi è il bonus di domani.'),
  ('I campioni si vedono nell''ultimo giro.'),
  ('Il talento vince le giornate, la squadra vince il mese.'),
  ('Ogni NO ti avvicina a un SÌ.'),
  ('Non serve essere i migliori di sempre: serve esserlo OGGI.'),
  ('Vendi come se fosse l''ultimo giorno del mese.'),
  ('La pressione è un privilegio.'),
  ('Il target non si guarda: si mangia.'),
  ('Grinta batte fortuna, sempre.'),
  ('Chi spinge adesso, ride a fine mese.'),
  ('Un cliente alla volta, fino in cima.'),
  ('Le scuse non attivano contratti.'),
  ('Oggi si scrive la classifica di domani.'),
  ('Il fuoco dentro batte il freddo fuori.'),
  ('Squadra che spinge non si batte.'),
  ('Sorridi, chiama, chiudi. Ripeti.'),
  ('L''ultimo sforzo conta doppio.'),
  ('Non fermarti quando sei stanco: fermati quando hai FINITO.'),
  ('Il mese non si chiude da solo: fatti sotto.'),
  ('Chi semina chiamate, raccoglie attivazioni.'),
  ('Testa alta, ritmo alto: si va.'),
  ('La differenza tra buono e grande è un altro tentativo.'),
  ('Il momento perfetto è ADESSO.'),
  ('Vinci la mattina e vincerai la giornata.'),
  ('Ogni cliente che entra è una finale.'),
  ('Non contare i giorni: fai contare i giorni.'),
  ('La disciplina pesa grammi, il rimpianto pesa tonnellate.'),
  ('Il sudore di oggi è l''applauso di domani.'),
  ('Prima regola: crederci. Seconda: dimostrarlo.'),
  ('Un venditore carico vale per tre.'),
  ('Fai parlare i numeri, il resto è rumore.'),
  ('Il limite è solo il punto da cui si riparte.'),
  ('Chi ha fame arriva primo.'),
  ('Il "quasi" non va a referto.'),
  ('Gioca ogni pallone come se fosse l''ultimo.'),
  ('Vietato mollare: è scritto sul contratto.'),
  ('Testa fredda, cuore caldo, penna veloce.'),
  ('Il futuro appartiene a chi chiama per primo.'),
  ('Batti il ferro finché il cliente è caldo.'),
  ('Meglio stanchi che pentiti.'),
  ('Chi non osa, resta a guardare.'),
  ('Le vendite amano i coraggiosi.'),
  ('Il gioco si fa duro? Perfetto, è il nostro campo.'),
  ('Non alzare bandiera bianca: alza il fatturato.'),
  ('La costanza è la scorciatoia che nessuno vede.'),
  ('Un giorno o il giorno uno: decidi tu.'),
  ('Più forte il vento, più forte il fuoco.'),
  ('L''occasione non bussa due volte: apri subito.'),
  ('Fai oggi quello che gli altri rimandano a domani.'),
  ('Il successo è la somma di piccoli sforzi ripetuti.'),
  ('Se fa paura, è la direzione giusta.'),
  ('Il campione si allena quando nessuno guarda.'),
  ('Niente pioggia, niente fiori: spingi.'),
  ('Ogni telefonata è una porta: aprile tutte.'),
  ('Vendere è servire: fallo alla grande.'),
  ('La fortuna aiuta chi richiama.'),
  ('Prometti meno, consegna di più, chiudi prima.'),
  ('Che sia un mese da raccontare.'),
  ('Il traguardo è solo l''inizio del prossimo record.'),
  ('Passione + metodo = numeri.'),
  ('Chi si ferma al primo no, non merita il sì.'),
  ('Fai rumore coi risultati, non con le parole.'),
  ('La squadra prima di tutto, il target subito dopo.'),
  ('Un sorriso al telefono si sente.'),
  ('Il cliente non compra il prodotto: compra TE.'),
  ('Puoi riposare a target chiuso.'),
  ('Le leggende non nascono in giornate facili.'),
  ('Il coraggio si vede alla firma.'),
  ('Non esistono clienti difficili, solo venditori arresi.'),
  ('Alza l''asticella: ci arrivi comunque.'),
  ('Vietato lamentarsi: consentito vincere.'),
  ('La strada per il bonus passa da qui.'),
  ('Ogni obiezione è una domanda travestita.'),
  ('Datti fuoco (di entusiasmo) e illumina il negozio.'),
  ('Prima il dovere, poi… un altro dovere. Poi il premio.'),
  ('Corri come se ti inseguisse il target.'),
  ('Il "ci penso" si scioglie col follow-up.'),
  ('Semplicemente: DAJE.'),
  ('Roma non fu venduta in un giorno, ma oggi si può.'),
  ('Facce toste, numeri veri.'),
  ('Il muro si abbatte una chiamata alla volta.'),
  ('Meno chat, più contratti.'),
  ('Fatti trovare pronto: la fortuna ha fretta.'),
  ('Il segreto? Non esiste. Esiste il lavoro.'),
  ('Se il piano A fallisce, l''alfabeto è lungo.'),
  ('Vinci tu, vince il negozio, vince la squadra.'),
  ('Un centimetro alla volta: è lì che si vince.'),
  ('Il pallone è sul dischetto: calcia.'),
  ('Le occasioni si creano, non si aspettano.'),
  ('Il freddo al telefono si scalda con la voce giusta.'),
  ('Serve un mese perfetto? No: serve un OGGI perfetto.'),
  ('Il tuo record personale ti sta aspettando.'),
  ('Niente panico: solo pratica.'),
  ('Trasforma la pausa caffè in pausa carica.'),
  ('Chi crede nei numeri, li vede crescere.'),
  ('L''energia è contagiosa: infetta il negozio.'),
  ('Su la testa, giù gli obiettivi (centrati).'),
  ('La paura di chiedere è l''unico vero KO.'),
  ('Ogni firma è una storia che inizia.'),
  ('Puntiamo alla luna: male che vada, record di zona.'),
  ('Sii il motivo per cui il cliente torna.'),
  ('Un grande mese è fatto di lunedì fortissimi.'),
  ('Attacca il mattino, difendi la sera.'),
  ('Niente vittorie comode: solo vittorie vere.'),
  ('La classifica è bugiarda solo per chi è sotto.'),
  ('Fai un passo in più: lì non c''è traffico.'),
  ('Il destino del mese è nelle tue chiamate.'),
  ('Gioca d''anticipo: richiama prima tu.'),
  ('L''entusiasmo chiude più del prezzo.'),
  ('Zero alibi, cento pezzi.'),
  ('Il tuo prossimo cliente è già in zona: trovalo.'),
  ('Vietato accontentarsi: il premio è più su.'),
  ('Le giornate storte esistono: le rimonte pure.'),
  ('Serve più fame che talento.'),
  ('Cuore, metodo e un pizzico di follia.'),
  ('Vendi col sorriso: è l''unico sconto gratuito.'),
  ('Il campo dice sempre la verità: allenati.'),
  ('Sfida te stesso di ieri: battilo.'),
  ('L''unica coda che vogliamo è quella in cassa.'),
  ('Pensa in grande, chiama in fretta.'),
  ('La motivazione ti sveglia, l''abitudine ti fa vincere.'),
  ('Un no al giorno non ferma chi ne vuole cento sì.'),
  ('Riscalda la voce: oggi si canta vittoria.'),
  ('Il talento è niente senza i richiami.'),
  ('Meglio un''azione imperfetta che un piano perfetto fermo.'),
  ('Ogni cliente merita il tuo 100%.'),
  ('Non abbassare il prezzo: alza il valore.'),
  ('La vetta è di chi non guarda indietro.'),
  ('Spingi ora: a fine mese si conta.'),
  ('Vinci in silenzio, festeggia fortissimo.'),
  ('Con la squadra giusta ogni target è piccolo.'),
  ('Nessuna pressione, solo diamanti in formazione.'),
  ('Il momento migliore per chiamare era ieri. Il secondo è adesso.'),
  ('Chi vuole, trova il tempo: chi non vuole, trova la scusa.'),
  ('L''appetito vien vendendo.'),
  ('Fatti un regalo: chiudi la pratica oggi.'),
  ('La perfezione è nemica della firma: procedi.'),
  ('Le grandi rimonte iniziano da un punto.'),
  ('Vendere è un sport di squadra giocato uno a uno.'),
  ('Chi domina il lunedì, domina la settimana.'),
  ('Un cliente felice ne porta tre.'),
  ('Il target teme solo una cosa: la tua costanza.'),
  ('Più richiami, meno rimpianti.'),
  ('Oggi niente pareggi: solo vittorie.'),
  ('Sii così bravo che non possano ignorarti.'),
  ('L''ambizione è il primo attrezzo del mestiere.'),
  ('Il negozio è il palco: fai lo spettacolo.'),
  ('Una firma tira l''altra.'),
  ('Non aspettare l''ispirazione: falla entrare in negozio.'),
  ('Diventa la giornata che gli altri racconteranno.'),
  ('Vietato dire "non si può": riformula e riprova.'),
  ('L''eccellenza è un''abitudine quotidiana.'),
  ('Chi ha un perché, trova ogni come.'),
  ('Piano piano si va lontano, ma oggi CORRIAMO.'),
  ('Sei a una chiamata dal cambio di passo.'),
  ('Il sogno è gratis: realizzarlo costa sudore.'),
  ('Le difficoltà preparano ai bonus straordinari.'),
  ('Vinci la paura e hai già mezzo sì.'),
  ('Il cliente sente se ci credi: credici.'),
  ('Ogni sera chiediti: ho dato tutto? Che la risposta sia SÌ.'),
  ('L''onda giusta si prende remando.'),
  ('Il gruppo che si carica insieme, chiude insieme.'),
  ('Non c''è ascensore per il target: si fanno le scale di corsa.'),
  ('Comincia dove sei, usa ciò che hai, chiudi ciò che puoi.'),
  ('La determinazione di oggi è la leggenda di domani.'),
  ('Cadere è concesso, rialzarsi è obbligatorio.'),
  ('Zitti e pedalare: il traguardo è dietro la curva.'),
  ('Il tuo unico rivale è il tuo numero di ieri.'),
  ('Se non ora, quando? Se non tu, chi?'),
  ('L''attesa non ha mai chiuso una pratica.'),
  ('Pensa come un campione: agisci come un martello.'),
  ('Ogni pratica chiusa è un mattone del tuo futuro.'),
  ('Il vento cambia: la vela sei tu.'),
  ('Fai della grinta la tua firma.'),
  ('Le statistiche premiano chi insiste.'),
  ('Sposta il limite: era solo un''opinione.'),
  ('Un mese leggendario inizia con un caffè e dieci chiamate.'),
  ('Chi gioca per la squadra, vince due volte.'),
  ('Il "ce l''ho fatta" vale ogni fatica.'),
  ('Non fermare la serie: un''altra firma, subito.'),
  ('Il carattere si vede al 28 del mese.'),
  ('Falli ricredere tutti.'),
  ('La tua energia decide il clima del negozio.'),
  ('Vendi oggi come vorresti raccontarlo domani.'),
  ('Il massimo è il minimo che ci chiediamo.'),
  ('Una chiamata coraggiosa vale dieci timide.'),
  ('Il bersaglio grosso si centra mirando alto.'),
  ('Che il mese ti trovi affamato.'),
  ('Il futuro premia i presenti: fatti trovare.'),
  ('Trasforma ogni dubbio in una domanda chiusa.'),
  ('Più veloce del "ci penso", più forte del "vedremo".'),
  ('L''ultimo chilometro decide la corsa: spingi.'),
  ('Fatti sentire: il target ha paura del rumore.'),
  ('Da qui alla vetta è tutta volata: DAJE!')
ON CONFLICT (testo) DO NOTHING;

NOTIFY pgrst, 'reload schema';
