-- 129: ORDINE MERCE — articoli ordinabili amministrabili (Luca 01/08 sera)
-- Le liste di "Prodotti da banco" ed "Extra" escono dal codice ed entrano a
-- DB: si gestiscono da Amministrazione → Ordine Merce (amministrativo in su),
-- come il catalogo e gli esiti. Seed = fotografia ESATTA delle liste cablate
-- di oggi, cosi' a tabella piena niente cambia finche' non si tocca qualcosa.
-- Le COVER restano fuori: si scelgono per modello di telefono, non da lista.
-- La pagina Ordine Merce fa fallback alle liste cablate se la tabella e' vuota.

create table if not exists public.ordine_merce_articoli (
  id uuid primary key default gen_random_uuid(),
  sezione text not null check (sezione in ('prodotti','extra')),
  categoria text not null,
  categoria_label text not null default '',
  categoria_icona text not null default '',
  nome text not null,
  ordine int not null default 0,
  attivo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists uq_om_articoli on public.ordine_merce_articoli (sezione, categoria, nome);

-- LEZIONE mig. 119: RLS OFF sulle tabelle nuove
alter table public.ordine_merce_articoli disable row level security;

insert into public.ordine_merce_articoli (sezione, categoria, categoria_label, categoria_icona, nome, ordine) values
('prodotti','pellicole','Pellicole','🛡️','PLV',0),
('prodotti','pellicole','Pellicole','🛡️','PLX',1),
('prodotti','pellicole','Pellicole','🛡️','Privacy',2),
('prodotti','cavi','Cavi','🔌','Type-C → USB',100),
('prodotti','cavi','Cavi','🔌','Type-C → Type-C',101),
('prodotti','cavi','Cavi','🔌','USB → Apple',102),
('prodotti','cavi','Cavi','🔌','Type-C → Apple',103),
('prodotti','travel','Travel','🔋','Originale Apple',200),
('prodotti','travel','Travel','🔋','Originale Samsung',201),
('prodotti','travel','Travel','🔋','Kit Completo',202),
('prodotti','travel','Travel','🔋','25W',203),
('prodotti','travel','Travel','🔋','30W',204),
('prodotti','travel','Travel','🔋','45W',205),
('prodotti','travel','Travel','🔋','Caricatore Wireless',206),
('prodotti','powerbank','Power Bank','🔋','5.000 mAh',300),
('prodotti','powerbank','Power Bank','🔋','10.000 mAh',301),
('prodotti','powerbank','Power Bank','🔋','20.000 mAh',302),
('prodotti','powerbank','Power Bank','🔋','MagSafe',303),
('prodotti','auricolari','Auricolari','🎧','Jack Audio 3.5',400),
('prodotti','auricolari','Auricolari','🎧','Type-C',401),
('prodotti','auricolari','Auricolari','🎧','Earbuds',402),
('prodotti','memoria','Memoria & Storage','💾','Memory Card 64GB',500),
('prodotti','memoria','Memoria & Storage','💾','Memory Card 128GB',501),
('prodotti','memoria','Memoria & Storage','💾','Memory Card 256GB',502),
('prodotti','memoria','Memoria & Storage','💾','Chiavetta USB-C 64GB',503),
('prodotti','memoria','Memoria & Storage','💾','Chiavetta USB-C 128GB',504),
('prodotti','senior','Telefoni Senior','👴','Brondi President',600),
('prodotti','senior','Telefoni Senior','👴','Brondi Magnum',601),
('prodotti','senior','Telefoni Senior','👴','Cordless Singolo',602),
('prodotti','senior','Telefoni Senior','👴','Cordless Doppio',603),
('prodotti','senior','Telefoni Senior','👴','Cordless Trio Panasonic',604),
('prodotti','senior','Telefoni Senior','👴','Cordless Trio Siemens',605),
('extra','cancelleria','Cancelleria','✏️','Penne',0),
('extra','cancelleria','Cancelleria','✏️','Evidenziatori',1),
('extra','cancelleria','Cancelleria','✏️','Pennarelli',2),
('extra','cancelleria','Cancelleria','✏️','Puntine',3),
('extra','cancelleria','Cancelleria','✏️','Spillatrice',4),
('extra','cancelleria','Cancelleria','✏️','Nastro Adesivo',5),
('extra','cancelleria','Cancelleria','✏️','Nastro Biadesivo',6),
('extra','cancelleria','Cancelleria','✏️','Nastro Carta',7),
('extra','cancelleria','Cancelleria','✏️','Forbici',8),
('extra','cancelleria','Cancelleria','✏️','Buste Trasparenti (Eurofogli)',9),
('extra','cancelleria','Cancelleria','✏️','Elastici',10),
('extra','cancelleria','Cancelleria','✏️','Blocco Appunti',11),
('extra','cancelleria','Cancelleria','✏️','Bianchino',12),
('extra','cancelleria','Cancelleria','✏️','Box Documenti',13),
('extra','cancelleria','Cancelleria','✏️','Rulli Dymo',14),
('extra','cancelleria','Cancelleria','✏️','Pellicola Plastificata',15),
('extra','cancelleria','Cancelleria','✏️','Attache',16),
('extra','pulizia','Pulizia','🧴','Panni Microfibra',100),
('extra','pulizia','Pulizia','🧴','Guanti Monouso',101),
('extra','pulizia','Pulizia','🧴','Sapone Mani',102),
('extra','pulizia','Pulizia','🧴','Spray Multiuso',103),
('extra','pulizia','Pulizia','🧴','WC Net',104),
('extra','pulizia','Pulizia','🧴','Scottex',105),
('extra','pulizia','Pulizia','🧴','Carta Igienica',106),
('extra','pulizia','Pulizia','🧴','Detersivo',107),
('extra','pulizia','Pulizia','🧴','Stracci',108),
('extra','pulizia','Pulizia','🧴','Sgrassatore',109),
('extra','pulizia','Pulizia','🧴','Sacchi Piccoli',110),
('extra','pulizia','Pulizia','🧴','Sacchi Grandi',111),
('extra','pulizia','Pulizia','🧴','Deodorante Spray',112),
('extra','pulizia','Pulizia','🧴','Profumatore',113),
('extra','pulizia','Pulizia','🧴','Spirito',114),
('extra','pulizia','Pulizia','🧴','Ammoniaca',115),
('extra','pulizia','Pulizia','🧴','Swiffer',116),
('extra','stampa','Stampa','🖨️','Rotoli POS',200),
('extra','stampa','Stampa','🖨️','Rotoli Cassa',201),
('extra','stampa','Stampa','🖨️','Inchiostro Nero',202),
('extra','stampa','Stampa','🖨️','Inchiostro Colore',203),
('extra','stampa','Stampa','🖨️','Carta A4 (risma)',204),
('extra','varie','Varie','🏪','Caffè Cialde',300),
('extra','varie','Varie','🏪','Acqua (bottiglie)',301),
('extra','varie','Varie','🏪','Bicchierini Caffè',302),
('extra','varie','Varie','🏪','Zucchero',303),
('extra','varie','Varie','🏪','Stecchette',304),
('extra','varie','Varie','🏪','Sapone Piatti',305),
('extra','varie','Varie','🏪','Buste Clienti',306),
('extra','varie','Varie','🏪','Batterie Mini Stilo AAA',307),
('extra','varie','Varie','🏪','Batterie Stilo AA',308),
('extra','elettronica','Elettronica','🖥️','Tastiera',400),
('extra','elettronica','Elettronica','🖥️','Mouse',401),
('extra','elettronica','Elettronica','🖥️','Pistola Barcode',402)
on conflict (sezione, categoria, nome) do nothing;

notify pgrst, 'reload schema';
