-- MODULO MAGAZZINO E GIACENZE (task Luca 12/08, riga 9d7fe69a) — fondamenta.
-- Consultazione universale stile Gestione Usati: inventario in tempo reale,
-- ricerca seriale con timeline, trasferimenti tra negozi con DDT.
-- Prima di oggi NON esisteva un modello dati di magazzino (solo l'elenco
-- articoli ordinabili di ordine_merce_articoli): si parte da qui.

-- L'UNITÀ serializzata: un telefono/SIM/accessorio identificato da un seriale.
create table if not exists mag_unita (
  id uuid primary key default gen_random_uuid(),
  seriale text not null,                 -- IMEI / ICCID / seriale generico
  tipo_seriale text not null default 'imei',   -- imei | sim | seriale
  codice text,                           -- codice articolo (listino)
  descrizione text not null,             -- es. "iPhone 15 128GB Nero"
  azienda text,                          -- ragione sociale proprietaria (codici pos_rt: T1/T2)
  negozio text not null,                 -- dove si trova ORA (o destinazione se in transito)
  stato text not null default 'disponibile',   -- disponibile | in_arrivo | in_transito | spedito | venduto
  valore numeric,                        -- valore unitario (per la colonna Valore della dashboard)
  caricato_il timestamptz not null default now(),
  caricato_da text,                      -- operatore che ha preso in carico
  venduto_il timestamptz,
  venduto_da text,
  contract_id text,                      -- vendita CRM collegata (scontrino/pratica)
  ddt_id uuid,                           -- DDT vivo (se in transito / in arrivo)
  storia jsonb not null default '[]',    -- timeline: [{quando, evento, negozio, operatore, note}]
  created_at timestamptz not null default now()
);
create index if not exists mag_unita_seriale on mag_unita (seriale);
create index if not exists mag_unita_negozio_stato on mag_unita (negozio, stato);
create unique index if not exists mag_unita_seriale_viva
  on mag_unita (seriale) where stato <> 'venduto';   -- lo stesso seriale può rivivere solo dopo la vendita

-- Il DDT di trasferimento tra negozi.
create table if not exists mag_ddt (
  id uuid primary key default gen_random_uuid(),
  numero int generated by default as identity,   -- progressivo documento
  da_negozio text not null,
  a_negozio text not null,
  stato text not null default 'in_transito',     -- in_transito | accettato | annullato
  creato_da text,
  creato_il timestamptz not null default now(),
  accettato_da text,
  accettato_il timestamptz,
  note text
);

-- il trigger rls_auto_enable accende RLS su ogni tabella nuova: senza policy
-- i salvataggi anon falliscono in silenzio (già successo sulle pay_*)
alter table mag_unita enable row level security;
drop policy if exists mag_unita_allow_all on mag_unita;
create policy mag_unita_allow_all on mag_unita for all using (true) with check (true);
alter table mag_ddt enable row level security;
drop policy if exists mag_ddt_allow_all on mag_ddt;
create policy mag_ddt_allow_all on mag_ddt for all using (true) with check (true);
