-- I TESTI WHATSAPP TORNANO QUELLI DEL PDF (Luca 31/08).
--
-- «Ti allego un file dove hai diverse tipologie di messaggi WhatsApp che
-- vanno messi al posto degli attuali.» I 50 testi c'erano tutti, ma solo 17
-- erano davvero uguali all'originale (misura del revisore): 19 divergevano
-- SOLO per le emoji perse e 14 anche nel testo.
--
-- PERCHÉ LE EMOJI ERANO SPARITE. Nel PDF non sono caratteri: sono nove
-- immagini PNG riusate 177 volte. Qualunque estrattore di testo le perde, e
-- infatti chi ha copiato i testi la prima volta ne ha lasciate indietro 30 su
-- 28 messaggi. Stavolta il file è stato riletto tenendo insieme le due cose —
-- i pezzi di testo con la loro posizione e i rettangoli delle immagini — e
-- rimontato nell'ordine in cui si leggono sulla pagina; le nove immagini sono
-- state guardate una per una per sapere quale emoji fossero
-- (👋 😊 📍 💬 📞 ✨ 📅 🕐 ✅).
--
-- E TORNA ANCHE IL GENERE DEL «LEI». Una migrazione precedente aveva provato
-- a rendere i testi neutri («L'ho cercata» → «L'ho cercato/a»): nel Lei di
-- cortesia il participio concorda col pronome, che è femminile — quindi la
-- forma del PDF era già corretta e la neutralizzazione la peggiorava, per
-- giunta applicata a 4 righe su 27.
--
-- I segnaposto restano quelli del CRM: [NOME] → {nome}, [OPERATORE] →
-- {caller}, [NEGOZIO] → {negozio}, [INDIRIZZO] → {indirizzo}, [GIORNO] →
-- {data_appuntamento}, [ORA] → {ora_appuntamento}.
--
-- Le due varianti «a fascia» di ogni gruppo conferma non stanno nel PDF: sono
-- del CRM (quando l'appuntamento ha la fascia e non l'ora) e non si toccano.

update wa_templates set corpo = 'Buongiorno {nome} 👋 😊 Sono {caller} del negozio {negozio} di {indirizzo} 📍. Ho provato a chiamarla per darle un breve aggiornamento. Quando le è più comodo sentirci: questa mattina o nel pomeriggio? Può rispondermi direttamente qui 💬. Grazie! 📞' where id = '4d51b98f-7421-49cd-8deb-b9a73811e879';   -- nr-lei · Lei — amichevole
update wa_templates set corpo = 'Salve {nome} ✨! Sono {caller} del punto vendita {negozio} di {indirizzo} 📍 😊 L''ho cercata poco fa, ma probabilmente era impegnata. Mi scriva pure qui quando ha due minuti, oppure mi indichi l''orario in cui preferisce essere richiamata.' where id = '12748060-d190-44b3-83bb-6c360ea17d4b';   -- nr-lei · Lei — informale e naturale
update wa_templates set corpo = 'Buongiorno {nome} 👋, sono {caller} del negozio {negozio} di {indirizzo} 📍 📞 Avrei bisogno di sentirla brevemente per completare un aggiornamento relativo alla sua linea. Appena può, mi risponda qui oppure mi indichi se preferisce essere richiamata al mattino o nel pomeriggio. Grazie!' where id = '3c0dd087-5187-4126-b49a-d1dfac924a02';   -- nr-lei · Lei — con priorità reale
update wa_templates set corpo = 'Buongiorno {nome} 👋, sono {caller} di {negozio}, {indirizzo} 📍 😊 Ho cercato di contattarla poco fa. Quando le è comodo, può rispondermi qui 💬 o indicarmi l''orario migliore per richiamarla.' where id = 'd272ddd6-9e8c-4614-839d-5fbd3053f32b';   -- nr-lei · Lei — variante 1
update wa_templates set corpo = 'Salve {nome} ✨ 📞 La contatto dal punto vendita {negozio} di {indirizzo} 📍. Non sono riuscito/a a raggiungerla telefonicamente; mi lasci pure un messaggio quando è disponibile.' where id = '1f95eda6-1c76-497b-b6d8-d0d43cc57ae0';   -- nr-lei · Lei — variante 2
update wa_templates set corpo = 'Gentile {nome}, sono {caller} del negozio {negozio}. Avrei bisogno di parlarle brevemente. Può richiamarmi oppure scrivermi qui 💬 quando ha un momento? Grazie 😊' where id = '7775aba7-f093-45c1-9782-d0272a94c009';   -- nr-lei · Lei — variante 3
update wa_templates set corpo = 'Buongiorno {nome} 👋! Ho provato a sentirla dal negozio {negozio} di {indirizzo} 📍. Se preferisce, mi indichi direttamente su WhatsApp una fascia oraria comoda per essere ricontattata 🕐' where id = '8b3491e9-e3e7-432f-8e6a-b79a1a0adde7';   -- nr-lei · Lei — variante 4
update wa_templates set corpo = 'Salve {nome} ✨, le scrive {caller} di {negozio} 😊 Vorrei darle un breve aggiornamento e non sono riuscito/a a trovarla al telefono. Preferisce sentirci al mattino o nel pomeriggio?' where id = 'bc01378d-4775-4dee-bf1c-7b61cf2c477d';   -- nr-lei · Lei — variante 5
update wa_templates set corpo = 'Buongiorno {nome} 👋, la cercavo dal punto vendita {negozio}, {indirizzo} 📍 📞 Quando riesce, mi risponda a questo messaggio: sarò felice di aggiornarla.' where id = '9985980d-7dcf-49f5-b171-f8bbf4855010';   -- nr-lei · Lei — variante 6
update wa_templates set corpo = 'Ciao {nome} 👋 😊 Sono {caller} del negozio {negozio} di {indirizzo} 📍. Ho provato a chiamarti per darti un breve aggiornamento. Quando ti è più comodo sentirci: questa mattina o nel pomeriggio? Puoi rispondermi direttamente qui 💬. Grazie! 📞' where id = '2a28d490-8837-4a46-87d6-91c05da549c6';   -- nr-tu · Tu — amichevole
update wa_templates set corpo = 'Ciao {nome} 👋! Ti ha cercato {caller} del punto vendita {negozio} di {indirizzo} 📍 😊 Probabilmente eri impegnato/a. Quando sei libero/a, mandami pure un messaggio oppure dimmi a che ora preferisci essere richiamato/a.' where id = '3d0f20f5-b9d6-4d9f-acdb-2ea0d95cd3c0';   -- nr-tu · Tu — informale e naturale
update wa_templates set corpo = 'Ciao {nome} 👋, sono {caller} del negozio {negozio} di {indirizzo} 📍 📞 Avrei bisogno di sentirti brevemente per completare un aggiornamento relativo alla tua linea. Appena puoi, rispondimi qui oppure dimmi se preferisci essere richiamato/a al mattino o nel pomeriggio. Grazie!' where id = '069ca1ea-fe75-4ac4-b3f2-9ef669f4fb83';   -- nr-tu · Tu — con priorità reale
update wa_templates set corpo = 'Ciao {nome} 👋, sono {caller} di {negozio}, {indirizzo} 📍 😊 Ho provato a chiamarti poco fa. Quando ti è comodo, scrivimi qui o dimmi l''orario migliore per richiamarti.' where id = '8610176a-d6d3-4179-bc99-afa2e829613c';   -- nr-tu · Tu — variante 1
update wa_templates set corpo = 'Ciao {nome} 👋 📞 Ti contatto dal punto vendita {negozio} di {indirizzo} 📍. Non sono riuscito/a a raggiungerti; lasciami pure un messaggio quando sei disponibile.' where id = 'b917e266-3e42-4594-b664-ee3e81d145f7';   -- nr-tu · Tu — variante 2
update wa_templates set corpo = 'Ciao {nome} 👋, sono {caller} del negozio {negozio}. Avrei bisogno di parlarti brevemente. Puoi richiamarmi oppure scrivermi qui 💬 quando hai un momento? Grazie 😊' where id = '7b7f4719-cdc6-4ef7-af1a-a0cad74a36d9';   -- nr-tu · Tu — variante 3
update wa_templates set corpo = 'Buongiorno {nome} 👋! Ho provato a sentirti dal negozio {negozio} di {indirizzo} 📍. Se preferisci, indicami su WhatsApp una fascia oraria comoda per richiamarti 🕐' where id = '17f585c1-8984-45f9-a7ba-6c598b390e70';   -- nr-tu · Tu — variante 4
update wa_templates set corpo = 'Ciao {nome} 👋, ti scrive {caller} di {negozio} 😊 Vorrei darti un breve aggiornamento e non sono riuscito/a a trovarti al telefono. Preferisci sentirci al mattino o nel pomeriggio?' where id = '2007b00d-23b8-4519-a78b-797acfb98fd3';   -- nr-tu · Tu — variante 5
update wa_templates set corpo = 'Ciao {nome} 👋, ti cercavo dal punto vendita {negozio}, {indirizzo} 📍 📞 Quando riesci, rispondimi a questo messaggio così posso aggiornarti.' where id = 'b367fad9-c338-452f-a214-722bada4c4ff';   -- nr-tu · Tu — variante 6
update wa_templates set corpo = 'Buongiorno {nome} 👋 😊 Sono {caller} del negozio WINDTRE di {indirizzo} 📍. Avevamo un appuntamento, ma ho visto che non è riuscito a venire e non l''ho trovata al telefono. Nessun problema: se desidera, possiamo concordare insieme un nuovo giorno e un orario più comodo 📅' where id = '225047da-9646-41d5-83fd-38e9dbea2206';   -- saltato-lei · Lei — amichevole
update wa_templates set corpo = 'Salve {nome} ✨! La aspettavamo oggi nel nostro punto vendita {negozio} di {indirizzo} 📍, ma immagino abbia avuto un imprevisto 😊 Ho provato anche a contattarla telefonicamente. Mi scriva pure qui quando vuole riprogrammare l''appuntamento.' where id = '70b1cc7a-5218-4c2a-b423-3fb881db245e';   -- saltato-lei · Lei — comprensiva
update wa_templates set corpo = 'Buongiorno {nome} 👋, sono {caller} del negozio {negozio} di {indirizzo} 📍. Non vedendola arrivare all''appuntamento, ho provato a chiamarla senza riuscire a raggiungerla 📞 Se desidera riprogrammarlo, mi scriva appena può: controllerò subito le disponibilità più vicine e le proporrò due alternative.' where id = '2ad7a5ed-584c-4628-916b-5a3e0ed167a3';   -- saltato-lei · Lei — con priorità
update wa_templates set corpo = 'Buongiorno {nome} 👋 😊 Oggi l''aspettavamo presso {negozio}, in {indirizzo} 📍. Non essendo riuscito/a a contattarla, le scrivo qui: se vuole, possiamo fissare un nuovo appuntamento.' where id = 'bf59403f-fe14-47ba-ac1a-de6fd642c9aa';   -- saltato-lei · Lei — variante 1
update wa_templates set corpo = 'Salve {nome} ✨, sono {caller} di {negozio}. Ho notato che non è riuscita a passare per l''appuntamento e immagino abbia avuto un imprevisto. Mi indichi pure quando preferisce riprogrammarlo.' where id = '303d531e-39e3-4dbe-91b8-2fa09a6d9e9e';   -- saltato-lei · Lei — variante 2
update wa_templates set corpo = 'Gentile {nome}, non l''abbiamo vista all''appuntamento previsto nel nostro negozio di {indirizzo} 📍 e non siamo riusciti a raggiungerla 📞 Se desidera, troviamo insieme una nuova disponibilità.' where id = '133cffe6-03fe-4c85-94d1-df9335786383';   -- saltato-lei · Lei — variante 3
update wa_templates set corpo = 'Buongiorno {nome} 👋! Nessun problema per l''appuntamento di oggi 😊 Quando le è possibile, mi scriva qui e le propongo un nuovo giorno e orario presso {negozio}.' where id = 'eea83ba3-b468-4da6-9810-c0d71d7cae2d';   -- saltato-lei · Lei — variante 4
update wa_templates set corpo = 'Salve {nome} ✨, ho provato a chiamarla dopo l''appuntamento presso {negozio}. Se desidera fissare una nuova data, mi risponda qui: verifico le disponibilità più vicine e le propongo due alternative 🕐' where id = 'aedd2a5b-80bb-49d2-8a9f-40619096e947';   -- saltato-lei · Lei — variante 5
update wa_templates set corpo = 'Buongiorno {nome} 👋, la contatto da {negozio}, {indirizzo} 📍. Non siamo riusciti a incontrarci come previsto; mi faccia sapere se desidera spostare l''appuntamento. Sarò lieto/a di aiutarla 😊' where id = 'd27e33c3-2f76-44c9-b5d8-f00ee86497ae';   -- saltato-lei · Lei — variante 6
update wa_templates set corpo = 'Ciao {nome} 👋 😊 Sono {caller} del negozio {negozio} di {indirizzo} 📍. Avevamo un appuntamento, ma ho visto che non sei riuscito/a a venire e non ti ho trovato al telefono. Nessun problema: scrivimi quando puoi e scegliamo insieme un nuovo giorno.' where id = '47750dc0-8c75-438b-af56-12eb90e12aae';   -- saltato-tu · Tu — amichevole
update wa_templates set corpo = 'Ciao {nome} 👋! Oggi ti aspettavamo nel punto vendita {negozio} di {indirizzo} 📍, ma immagino sia successo un imprevisto 😊 Ho provato anche a chiamarti. Se vuoi recuperare l''appuntamento, dimmi pure quando ti farebbe più comodo passare.' where id = '2fe2e7a4-52ba-4882-8145-d2bedd5a27eb';   -- saltato-tu · Tu — comprensiva
update wa_templates set corpo = 'Ciao {nome} 👋, sono {caller} del negozio {negozio} di {indirizzo} 📍. Non vedendoti arrivare all''appuntamento, ho provato a contattarti 📞 Se vuoi riprogrammarlo, scrivimi appena riesci: controllo subito le disponibilità più vicine e ti propongo due alternative.' where id = '0794d816-80dc-4614-98c8-dcfa2409f834';   -- saltato-tu · Tu — con priorità
update wa_templates set corpo = 'Ciao {nome} 👋 😊 Oggi ti aspettavamo presso {negozio}, in {indirizzo} 📍. Non essendo riuscito/a a contattarti, ti scrivo qui: se vuoi, possiamo fissare un nuovo appuntamento.' where id = '60a24ec9-348b-421f-b3fe-d0ea5fc81d90';   -- saltato-tu · Tu — variante 1
update wa_templates set corpo = 'Ciao {nome} 👋, sono {caller} di {negozio}. Ho visto che non sei riuscito/a a passare e immagino abbia avuto un imprevisto. Dimmi pure quando preferisci riprogrammare.' where id = '3fafeb98-6013-445c-be3e-5269e08bea3c';   -- saltato-tu · Tu — variante 2
update wa_templates set corpo = 'Ciao {nome} 👋, non ti abbiamo visto all''appuntamento previsto nel nostro negozio di {indirizzo} 📍 e non siamo riusciti a raggiungerti 📞 Se vuoi, troviamo insieme una nuova disponibilità.' where id = '96a91e8b-0ca9-4ea3-ae74-d884bf0f4e88';   -- saltato-tu · Tu — variante 3
update wa_templates set corpo = 'Buongiorno {nome} 👋! Nessun problema per l''appuntamento di oggi 😊 Quando puoi, scrivimi qui e ti propongo un nuovo giorno e orario presso {negozio}.' where id = '68b29284-dcab-4656-bf30-18d7692490df';   -- saltato-tu · Tu — variante 4
update wa_templates set corpo = 'Ciao {nome} 👋, ho provato a chiamarti dopo l''appuntamento presso {negozio}. Se vuoi fissare una nuova data, rispondimi qui: controllo le disponibilità più vicine e ti propongo due alternative 🕐' where id = '98c4fa6d-5a60-4d0c-860d-b913ca4a5a29';   -- saltato-tu · Tu — variante 5
update wa_templates set corpo = 'Ciao {nome} 👋, ti contatto da {negozio}, {indirizzo} 📍. Non siamo riusciti a incontrarci come previsto; fammi sapere se vuoi spostare l''appuntamento. Ti aiuto volentieri 😊' where id = '359db285-e535-45a0-ae6e-ed9c670d4e7e';   -- saltato-tu · Tu — variante 6
update wa_templates set corpo = 'Buongiorno {nome} 👋 😊 Le confermo l''appuntamento presso il negozio {negozio}, in {indirizzo} 📍, per 📅 {data_appuntamento} alle ore 🕐 {ora_appuntamento}. Per qualsiasi necessità può rispondere direttamente a questo messaggio 💬. La aspettiamo! ✅' where id = '1bb672cf-c164-407b-9212-7705c77a33b8';   -- conferma-lei · Lei — cordiale
update wa_templates set corpo = 'Salve {nome} ✨! Il suo appuntamento è confermato per 📅 {data_appuntamento} alle 🕐 {ora_appuntamento} presso {negozio}, in {indirizzo} 📍 😊 Saremo lieti di accoglierla. Se dovesse avere un imprevisto, ci avvisi pure qui.' where id = '2d013e77-a457-4e18-8028-c7c8a573e4b4';   -- conferma-lei · Lei — calda e accogliente
update wa_templates set corpo = 'Gentile {nome}, le ricordiamo l''appuntamento fissato per 📅 {data_appuntamento} alle ore 🕐 {ora_appuntamento} nel punto vendita {negozio} di {indirizzo} 📍 🕐 In caso di ritardo o necessità di modifica, può scriverci su WhatsApp. A presto!' where id = 'cc21ee32-b99e-4a72-a7ac-4717d8b850bf';   -- conferma-lei · Lei — promemoria chiaro
update wa_templates set corpo = 'Buongiorno {nome} 👋 ✅ Appuntamento confermato per 📅 {data_appuntamento} alle 🕐 {ora_appuntamento} presso {negozio}, {indirizzo} 📍. Per qualsiasi variazione può scriverci qui 💬. A presto!' where id = 'f2db21bd-44ba-4d29-8aed-c8fd0728c9fb';   -- conferma-lei · Lei — variante 1
update wa_templates set corpo = 'Salve {nome} ✨ 😊 La aspettiamo 📅 {data_appuntamento} alle ore 🕐 {ora_appuntamento} nel punto vendita {negozio} di {indirizzo} 📍. Se ha bisogno di modificare l''orario, ci avvisi con un messaggio.' where id = '40d1d54b-5114-4b71-a348-acbabae47794';   -- conferma-lei · Lei — variante 2
update wa_templates set corpo = 'Gentile {nome}, questo è il promemoria del suo appuntamento: 📅 {data_appuntamento}, ore 🕐 {ora_appuntamento}, presso {negozio} - {indirizzo} 📍 🕐 A presto!' where id = '09ee1a5a-5af2-4e46-82d0-926c1be1793f';   -- conferma-lei · Lei — variante 3
update wa_templates set corpo = 'Buongiorno {nome} 👋, abbiamo riservato per lei l''appuntamento di 📅 {data_appuntamento} alle 🕐 {ora_appuntamento} nel negozio {negozio}, in {indirizzo} 📍 ✅ Restiamo disponibili qui su WhatsApp.' where id = '64bf316f-be14-4c34-b292-18046e943303';   -- conferma-lei · Lei — variante 4
update wa_templates set corpo = 'Ciao {nome} 👋 😊 Ti confermo l''appuntamento presso il negozio {negozio}, in {indirizzo} 📍, per 📅 {data_appuntamento} alle ore 🕐 {ora_appuntamento}. Per qualsiasi necessità puoi rispondere direttamente a questo messaggio 💬. Ti aspettiamo! ✅' where id = 'e3189bc9-db81-4089-800b-ce2b46c848e4';   -- conferma-tu · Tu — cordiale
update wa_templates set corpo = 'Ciao {nome} 👋! Il tuo appuntamento è confermato per 📅 {data_appuntamento} alle 🕐 {ora_appuntamento} presso {negozio}, in {indirizzo} 📍 😊 Saremo felici di accoglierti. Se dovessi avere un imprevisto, avvisaci pure qui.' where id = '2385b515-8303-4e26-9652-07a88da2622a';   -- conferma-tu · Tu — calda e accogliente
update wa_templates set corpo = 'Ciao {nome} 👋, ti ricordiamo l''appuntamento fissato per 📅 {data_appuntamento} alle ore 🕐 {ora_appuntamento} nel punto vendita {negozio} di {indirizzo} 📍 🕐 In caso di ritardo o se vuoi modificare l''orario, scrivici pure qui 💬. A presto!' where id = 'ba247ff9-ecfb-44d9-827d-8ad91116911a';   -- conferma-tu · Tu — promemoria chiaro
update wa_templates set corpo = 'Ciao {nome} 👋 ✅ Appuntamento confermato per 📅 {data_appuntamento} alle 🕐 {ora_appuntamento} presso {negozio}, {indirizzo} 📍. Per qualsiasi variazione puoi scriverci qui 💬. A presto!' where id = '52192b7a-bf0d-4e63-ab9a-2a07b87c19e2';   -- conferma-tu · Tu — variante 1
update wa_templates set corpo = 'Ciao {nome} 👋 😊 Ti aspettiamo 📅 {data_appuntamento} alle ore 🕐 {ora_appuntamento} nel punto vendita {negozio} di {indirizzo} 📍. Se hai bisogno di modificare l''orario, avvisaci con un messaggio.' where id = '97aa3196-39fb-4d1e-b237-9aeef3989e51';   -- conferma-tu · Tu — variante 2
update wa_templates set corpo = 'Ciao {nome} 👋, ecco il promemoria del tuo appuntamento: 📅 {data_appuntamento}, ore 🕐 {ora_appuntamento}, presso {negozio} - {indirizzo} 📍 🕐 A presto!' where id = '5c9670be-2793-4d30-9e6b-439becf62826';   -- conferma-tu · Tu — variante 3
update wa_templates set corpo = 'Buongiorno {nome} 👋, abbiamo riservato per te l''appuntamento di 📅 {data_appuntamento} alle 🕐 {ora_appuntamento} nel negozio {negozio}, in {indirizzo} 📍 ✅ Restiamo disponibili qui su WhatsApp.' where id = 'c72e9a26-1d1c-4b1f-affc-68899e3b6a5e';   -- conferma-tu · Tu — variante 4
