-- SEGNALAZIONE VENDITA COLLEGATA (Luca 24/08): il caller segnala che
-- dall'appuntamento di una lead è nata una vendita A NOME DIVERSO
-- (es. la moglie). L'amministrazione approva collegando una o più
-- vendite coerenti (nome+cognome, negozio, giorno) → cooperation.
create table if not exists public.caller_vendite_segnalate (
    id bigint generated by default as identity primary key,
    call_id uuid not null,
    caller text not null,
    cliente_nome text not null,
    cliente_cognome text not null,
    negozio text not null,
    giorno date not null,
    nota text,
    stato text not null default 'in_attesa' check (stato in ('in_attesa', 'approvata', 'rifiutata')),
    contract_ids jsonb not null default '[]'::jsonb,
    decisa_da text,
    decisa_il timestamptz,
    nota_decisione text,
    created_at timestamptz not null default now()
);
create index if not exists idx_cvs_stato on public.caller_vendite_segnalate (stato);
create index if not exists idx_cvs_call on public.caller_vendite_segnalate (call_id);
alter table public.caller_vendite_segnalate enable row level security;
drop policy if exists caller_vendite_segnalate_all on public.caller_vendite_segnalate;
create policy caller_vendite_segnalate_all on public.caller_vendite_segnalate
    for all using (true) with check (true);
